### ISSUE TITLE
Ignore archived projects when scanning CICD variables

### ISSUE THREAD

**Issue by Stan0304** [PaperMtn/gitlab-watchman#1]
## Description

When searching for CICD variables, gitlab-watchman enumerates projects first and then call the GitLab API /variables. This endpoint is not available for archived projects leading to an error stopping gitlab-watchman analysis.  
The error : `403 Client Error: Forbidden for url: https://gitlab.softfactory-accor.net/api/v4/projects/141/variables`.

## Proposal

When enumerating projects, gitlab-watchman applies a filter to ignore archived project. 

/label ~Bug

**Comment by PaperMtn** [comment]
Looking at this, I think GitLab may have made some changes to how the API works for variables: https://docs.gitlab.com/ee/api/project_level_variables.html

It now specifically says the project must be "owned by the authenticated user". I have tried removing archived projects and it is still the same problem.

I will continue to look and see if there is a workaround, but if not the feature may have to be removed.

**Comment by PaperMtn** [comment]
Changes in API mean variable searching is no longer possible. This feature has been removed in the latest release
